from .outlet_serializer import OutletListSerializer, OutletCreateSerializer,OutletSerializer
from .category_serializer import CategoryListSerializer, CategoryCreateSerializer
from .product_serializer import ProductListSerializer

