from .outlet_serializer import OutletListSerializer, OutletCreateSerializer, OutletSerializer, OutletRetrieveSerializer
from .category_serializer import CategoryListSerializer, CategoryCreateSerializer
from .product_serializer import ProductListSerializer, ProductUpdateSerializer, ProductCreateSerializer
